{
  "Id": 50331811,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "function IsSpecificUnitType takes nothing returns boolean\r\n    local integer unitId = GetUnitTypeId(GetFilterUnit())\r\n    return (unitId == 'h01B' or unitId == 'h01K')\r\nendfunction\r\n\r\nfunction IsUnitAlive takes nothing returns boolean\r\n    return IsUnitAliveBJ(GetFilterUnit())\r\nendfunction\r\n\r\nfunction IsUnitAllyPlayer takes nothing returns boolean\r\n    return IsUnitAlly(GetFilterUnit(), udg_AI_TempPlayer)\r\nendfunction\r\n\r\nfunction IsUnitAliveAndAlly takes nothing returns boolean\r\n    return GetBooleanAnd(IsUnitAlive(), IsUnitAllyPlayer())\r\nendfunction\r\n\r\nfunction IsSpecificUnitAliveAndAlly takes nothing returns boolean\r\n    return GetBooleanAnd(IsSpecificUnitType(), IsUnitAliveAndAlly())\r\nendfunction\r\n\r\nfunction IsDistanceGreaterThan450 takes nothing returns boolean\r\n    return DistanceBetweenPoints(udg_TempPoint_Loop[1], udg_Spell_Caster_Point) > 450.00\r\nendfunction\r\n\r\nfunction IsGroupCountGreaterOrEqual2 takes nothing returns boolean\r\n    return CountUnitsInGroup(udg_TempGroup) >= 2\r\nendfunction\r\n\r\nfunction Trig_AI_Lane_Phase_Actions takes nothing returns nothing\r\n    set udg_Spell_Caster_Point = GetUnitLoc(udg_AI_TempUnit)\r\n    set udg_TempGroup = GetUnitsInRangeOfLocMatching(650.00, udg_Spell_Caster_Point, Condition(function IsSpecificUnitAliveAndAlly))\r\n    \r\n    if ( IsGroupCountGreaterOrEqual2() ) then\r\n        set udg_TempPoint_Loop[1] = GetUnitLoc(udg_AI_Tower_Target[udg_AI_Loop])\r\n        set udg_TempPoint_Loop[2] = PolarProjectionBJ(udg_TempPoint_Loop[1], GetRandomReal(200.00, 300.00), 270.00)\r\n        call IssuePointOrderLoc(udg_AI_TempUnit, \"attack\", udg_TempPoint_Loop[2])\r\n    else\r\n        set udg_TempPoint_Loop[1] = GetUnitLoc(udg_AI_Tower_Guard[udg_AI_Loop])\r\n        set udg_TempPoint_Loop[2] = PolarProjectionBJ(udg_TempPoint_Loop[1], GetRandomReal(250.00, 450.00), GetRandomDirectionDeg())\r\n        if ( IsDistanceGreaterThan450() ) then\r\n            call IssuePointOrderLoc(udg_AI_TempUnit, \"move\", udg_TempPoint_Loop[1])\r\n        else\r\n            call IssuePointOrderLoc(udg_AI_TempUnit, \"attack\", udg_TempPoint_Loop[2])\r\n        endif\r\n    endif\r\n    \r\n    call RemoveLocation(udg_TempPoint_Loop[1])\r\n    call RemoveLocation(udg_TempPoint_Loop[2])\r\n    call DestroyGroup(udg_TempGroup)\r\n    call RemoveLocation(udg_Spell_Caster_Point)\r\nendfunction\r\n\r\n//===========================================================================\r\nfunction InitTrig_AI_Lane_Phase takes nothing returns nothing\r\n    set gg_trg_AI_Lane_Phase = CreateTrigger()\r\n    call TriggerAddAction(gg_trg_AI_Lane_Phase, function Trig_AI_Lane_Phase_Actions)\r\nendfunction",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}