{
  "Id": 50331840,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": true,
  "Script": "function Trig_Preload_Loop_Actions takes nothing returns nothing\r\n// -----------------------PRELOAD ITEMS-----------------------\r\n    \r\n\r\n// -----------------------PRELOAD ABILITY-----------------------\r\n    //01\r\n    call PreloadAbility('A01T')\r\n    //02\r\n    call PreloadAbility('A037')\r\n    //03\r\n    call PreloadAbility('A0BO')\r\n    //04\r\n    call PreloadAbility('A0BQ')\r\n    //05\r\n    call PreloadAbility('Arav')\r\n    //06\r\n    call PreloadAbility('A07V')\r\n    //07\r\n    call PreloadAbility('A0CX')\r\n    //08\r\n    call PreloadAbility('A0EF')\r\n    //09\r\n    call PreloadAbility('A0EE')\r\n    //10\r\n    call PreloadAbility('A07N')\r\n    //11\r\n    call PreloadAbility('A0BZ')\r\n    //12\r\n    call PreloadAbility('A0EN')\r\n    //13\r\n    call PreloadAbility('A061')\r\n    //14\r\n    call PreloadAbility('A041')\r\n    //15\r\n    call PreloadAbility('A02G')\r\n    //16 Shop Level 1 - 02\r\n    call PreloadAbility('A0FS')\r\n    //17 Shop Level 3 - 02\r\n    call PreloadAbility('A0FU')\r\n    //18 Shop Level 5 - 02\r\n    call PreloadAbility('A0FV')\r\n    //19 Shop Level 9 - 02\r\n    call PreloadAbility('A0EQ')\r\n    //20 Orb of Lighting\r\n    call PreloadAbility('A0BY')\r\n    //21 Thunder Guard\r\n    call PreloadAbility('A0C5')\r\n    //22 Flare of Sight\r\n    call PreloadAbility('A01U')\r\n    //23 Battle Hammer Stun\r\n    call PreloadAbility('A09K')\r\n    //24 Eruption - Stun - BOSS\r\n    call PreloadAbility('A01P')\r\n    //25 Cooldown - Cargo Hold\r\n    call PreloadAbility('Sch2')\r\n    //26 ATTACK COUNT SYSTEM\r\n    call PreloadAbility('A0CP')\r\n    \r\n    //--------------------------------------\r\n    //01 SFS - Blink\r\n    call PreloadAbility('A0C4')\r\n    //02 SFS - Ensnare\r\n    call PreloadAbility('A0CA')\r\n    //03 SFS - Reveal\r\n    call PreloadAbility('A01X')\r\n    //04 SFS - Silence\r\n    call PreloadAbility('A01Y')\r\n    \r\n    //--------------------------------------\r\n    //01 Cooldown Ice Blade\r\n    call PreloadAbility('A0H4')\r\n    //02 Cooldown Battle Hammer\r\n    call PreloadAbility('A0H5')\r\n    //03 Cooldown Thunder Guard\r\n    call PreloadAbility('A0H6')\r\n    //04 Call for Home\r\n    call PreloadAbility('A088')\r\n    //05 Cooldown Lighting Items\r\n    call PreloadAbility('A095')\r\n\r\n\r\nendfunction\r\n\r\n//===========================================================================\r\nfunction InitTrig_Preload_Loop takes nothing returns nothing\r\n    set gg_trg_Preload_Loop = CreateTrigger(  )\r\n    call TriggerAddAction( gg_trg_Preload_Loop, function Trig_Preload_Loop_Actions )\r\nendfunction\r\n\r\n",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}